hydrogarden:
  service-name: hg-backend
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  clerk:
    jwks:
      refresh-ms: 3600000
      url: "https://sound-lemming-80.clerk.accounts.dev/.well-known/jwks.json"

logging:
  level:
    org:
      apache:
        catalina: DEBUG
        tomcat: DEBUG
  file:
    name: ./hg-logs/hg-backend/hg_backend.log
server:
  tomcat:
    basedir: file:/tmp
    accesslog:
      enabled: true
      rotate: false
      pattern: "%h %l %u %t \"%r\" %s %b"
      prefix: access_log
      directory: /app/hg-logs/hg-backend
      suffix: .log
  servlet:
    context-path: "/${hydrogarden.service-name}"
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hydrogarden.mysql.host}:${hydrogarden.mysql.port}/${hydrogarden.service-name}
    password: ${hydrogarden.mysql.password}
    username: ${hydrogarden.mysql.username}
  jpa:
    hibernate:
      ddl-auto: validate
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/ddl
      - classpath:db/migration/dml
    baseline-on-migrate: false
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    host: ${hydrogarden.rabbitmq.host}
    port: ${hydrogarden.rabbitmq.port}
    username: ${hydrogarden.rabbitmq.username}
    password: ${hydrogarden.rabbitmq.password}